openapi: 3.1.0
info:
  title: AI Todo Chatbot API
  description: Chat endpoint for natural language task management
  version: 1.0.0

servers:
  - url: /api
    description: Backend API

paths:
  /chat:
    post:
      summary: Send chat message
      description: |
        Send a natural language message to the AI chatbot.
        Returns a streaming response (SSE) with the assistant's reply.
      operationId: sendChatMessage
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
            examples:
              newConversation:
                summary: Start new conversation
                value:
                  message: "Add a task to buy groceries"
              continueConversation:
                summary: Continue existing conversation
                value:
                  conversation_id: 123
                  message: "What tasks do I have?"
      responses:
        '200':
          description: Streaming response (SSE)
          content:
            text/event-stream:
              schema:
                $ref: '#/components/schemas/ChatStreamEvent'
              examples:
                textDelta:
                  summary: Text delta event
                  value: |
                    data: {"type": "text_delta", "content": "I've added"}

                    data: {"type": "text_delta", "content": " a task"}

                    data: {"type": "done", "conversation_id": 123, "tool_calls": [{"tool": "add_task", "result": {"task_id": 1}}]}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Message cannot be empty"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Invalid or expired token"
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Conversation not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Failed to process message"

  /conversations:
    get:
      summary: List conversations
      description: Get list of user's conversations, ordered by most recent
      operationId: listConversations
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
          description: Maximum number of conversations to return
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'
        '401':
          description: Unauthorized

  /conversations/{conversation_id}:
    get:
      summary: Get conversation with messages
      description: Get a specific conversation with all its messages
      operationId: getConversation
      security:
        - bearerAuth: []
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Conversation with messages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationWithMessages'
        '401':
          description: Unauthorized
        '404':
          description: Conversation not found

    delete:
      summary: Delete conversation
      description: Delete a conversation and all its messages
      operationId: deleteConversation
      security:
        - bearerAuth: []
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Conversation deleted
        '401':
          description: Unauthorized
        '404':
          description: Conversation not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from Better Auth

  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        conversation_id:
          type: integer
          description: ID of existing conversation (omit to start new)
          example: 123
        message:
          type: string
          minLength: 1
          maxLength: 4000
          description: User's natural language message
          example: "Add a task to buy groceries"

    ChatStreamEvent:
      type: object
      description: Server-Sent Event payload
      oneOf:
        - $ref: '#/components/schemas/TextDeltaEvent'
        - $ref: '#/components/schemas/DoneEvent'
        - $ref: '#/components/schemas/ErrorEvent'

    TextDeltaEvent:
      type: object
      required:
        - type
        - content
      properties:
        type:
          type: string
          enum: [text_delta]
        content:
          type: string
          description: Partial text content

    DoneEvent:
      type: object
      required:
        - type
        - conversation_id
      properties:
        type:
          type: string
          enum: [done]
        conversation_id:
          type: integer
          description: ID of the conversation
        tool_calls:
          type: array
          items:
            $ref: '#/components/schemas/ToolCall'
          description: MCP tools that were invoked

    ErrorEvent:
      type: object
      required:
        - type
        - error
      properties:
        type:
          type: string
          enum: [error]
        error:
          type: string
          description: Error message

    ToolCall:
      type: object
      properties:
        tool:
          type: string
          enum: [add_task, list_tasks, complete_task, delete_task, update_task]
          description: Name of the MCP tool invoked
        args:
          type: object
          description: Arguments passed to the tool
        result:
          type: object
          description: Result returned by the tool

    Conversation:
      type: object
      required:
        - id
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          example: 123
        created_at:
          type: string
          format: date-time
          example: "2025-12-03T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2025-12-03T10:35:00Z"

    ConversationWithMessages:
      allOf:
        - $ref: '#/components/schemas/Conversation'
        - type: object
          properties:
            messages:
              type: array
              items:
                $ref: '#/components/schemas/Message'

    Message:
      type: object
      required:
        - id
        - role
        - content
        - created_at
      properties:
        id:
          type: integer
          example: 456
        role:
          type: string
          enum: [user, assistant]
          example: "user"
        content:
          type: string
          example: "Add a task to buy groceries"
        tool_calls:
          type: array
          items:
            $ref: '#/components/schemas/ToolCall'
          nullable: true
        created_at:
          type: string
          format: date-time
          example: "2025-12-03T10:30:00Z"

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
